### PR TITLE
fix: Fetching Sender Name from .env

### PR DESCRIPTION
**Pull request by JemCdo**
Hi there @tomsgad 
I've tried to implementing using Sender Name from .env file , can you review , test and refactor if required (am not expert in package development), Thanks

### CODE REVIEW

**Comment by tomsgad** [comment]
Ok, let me check it and merge!

**Comment by tomsgad** [comment]
Fixed with the recent push!

**Comment by tomsgad** [comment]
Am not sure... Bt my best guess is, you need to have the project secure. Are you using valet?

**Comment by JemCdo** [comment]
Hapana , Just simple dev environment (xammp) ... nimejaribu pia on digital Ocean am getting the same error10:38, 9 May 2021, Thomson Maguru ***@***.***>:
Am not sure... Bt my best guess is, you need to have the project secure. Are you using valet?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Regards,James Emanuel

**Comment by tomsgad** [comment]
Got two links that might help you fix your issue. [link one](https://noorsplugin.com/how-to-fix-curl-error-60-ssl-certificate-problem-unable-to-get-local-issuer-certificate/) and [link](https://medium.com/@narendravaghela/how-to-fix-curl-error-60-ssl-certificate-problem-80e7dafafa57#:~:text=Sometimes%2C%20when%20we%20make%20a,request%20using%20self-signed%20certificate.)

**Comment by tomsgad** [comment]
Hi @JemCdo just got the fix for the error, at least temporary. Jaribu ku update, it should be working.

**Comment by JemCdo** [comment]
Hi Bro Niaje, Sorry for the late reply, I've been occupied with other work
... I will check it out and let you know

**Comment by JemCdo** [comment]
Hi Bro Niaje, I've updated and everything works fine now. Thanks

**Comment by tomsgad** [comment]
Cool Chief. Am doing a total reshuffle ya the app. Nataka kuongeza payments, ussd and all that viko kwenye Beem.

Also i need some help documenting kama you have some time.

**Pull request closed without merging**
